# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

    dynamic_conveyor_lift_tuner_controller:
      type: dynamic_conveyor_lift_tuner_controller/DynamicConveyorLiftTunerController

    gpio_controller:
      type: gpio_controller/GPIOController

velocity_controller:
  ros__parameters:
    joints:
      - conveyor_lift_left

position_controller:
  ros__parameters:
    joints:
      - conveyor_lift_left            

gpio_controller:
  ros__parameters:  
    outputs:
     - push_front
     - pull_back
     - dummy
     - push_front2
     - pull_back2
     - dummy2
    output_mapping:
      push_front:
        interface: conveyor_lift_left/gpio_output_0
      pull_back:
        interface: conveyor_lift_left/gpio_output_1
      dummy:
        interface: conveyor_lift_left/gpio_output_2
      push_front2:
        interface: conveyor_lift_right/gpio_output_0
      pull_back2:
        interface: conveyor_lift_right/gpio_output_1
      dummy2:
        interface: conveyor_lift_right/gpio_output_2          